product: ubuntu2004
full_name: Ubuntu 2004
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes_root: "../shared/applicability"
cpes: []
  # new_product:
  #   name: "cpe:/o:ubuntu:2004"
  #   title: "Ubuntu 2004"
  #   check_id: installed_OS_is_ubuntu2004
