product: al2
full_name: AmazonLinux 2
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes_root: "../shared/applicability"
cpes: []
  # new_product:
  #   name: "cpe:/o:al:2"
  #   title: "AmazonLinux 2"
  #   check_id: installed_OS_is_al2
